ProjectManager.Web/Areas/Authentication/Controllers/RegisterController.cs
using DomainObjects;
using ProjectManager.Web.Areas.Authentication.ViewModels;
using System;
using System.Data.Entity.Validation;
using System.Web.Mvc;

namespace ProjectManager.Web.Areas.Authentication.Controllers
{
    public class RegisterController : Controller
    {
        private UserResponsibilityRepository _urr = new UserResponsibilityRepository();
        private UserRepository _ur = new UserRepository();
        ModelMapper mapper = new ModelMapper();
        // GET: Authentication/Register
        public ActionResult Index()
        {
            ViewBag.ResponsibilityId = new SelectList(_urr.GetAll(), "Id", "Responsibility");
            ViewBag.Title = "Create a New Account";
            return View();
        }

        [HttpPost]
        public ActionResult RegisterNewUser(RegistrationModel newRegistration)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");

            try
            {
                User newUser = new User("User");
                if (!mapper.Map<RegistrationModel, User>(newRegistration, newUser))
                    throw new InvalidOperationException();
                newUser.SetPasswordHash(newUser.Password); ///Hashes the password using Bcrypt.
                _ur.AddUser(newUser);
                return RedirectToAction("Welcome", "Home", new { area = "General" });
            }
            catch (InvalidOperationException)
            {
                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException)
            {
                return RedirectToAction("Index");
            }
        }


    }
}

ProjectManager.Web/Areas/Authentication/Views/Register/Index.cshtml
@model DomainObjects.User


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<script src="~/Scripts/_references.js"></script>
@using (Html.BeginForm("RegisterNewUser","Register", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, htmlAttributes :new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.confirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.confirmPassword, htmlAttributes: new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsibilityId,"Responsibility", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResponsibilityId",null,htmlAttributes: new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.ResponsibilityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}